// Regenerates src/styles/tokens.css from src/design/tokens.mjs.
// Run after editing tokens: node scripts/sync-tokens.mjs
import { writeFileSync } from "node:fs";
import { cssVars } from "../src/design/tokens.mjs";

const lines = Object.entries(cssVars)
  .map(([name, value]) => `    --${name}: ${value};`)
  .join("\n");

const css = `/* GENERATED by scripts/sync-tokens.mjs from src/design/tokens.mjs.
 * Do not edit by hand — edit the tokens and re-run the script. */
:root {
${lines}
}
`;

writeFileSync("src/styles/tokens.css", css);
console.log(`src/styles/tokens.css written (${Object.keys(cssVars).length} vars)`);
